services:
  api:
    container_name: api
    image: api
    build: .
    ports:
      - 8080:8080
    environment:
      - DB_USER=marcelo
      - DB_PASSWORD=1234
      - DB_HOST=database
      - DB_PORT=5432
      - DB=products_management
    depends_on:
      database:
        condition: service_healthy
  database:
    container_name: database
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=marcelo
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=products_management
    volumes:
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: psql -U marcelo products_management || exit 1
      interval: 1s
      timeout: 5s
      retries: 5
      start_period: 30s
